Add PR title and body checks

diff --git a/.github/workflows/pr_opened.yml b/.github/workflows/pr_opened.yml
--- a/.github/workflows/pr_opened.yml
+++ b/.github/workflows/pr_opened.yml
@@ -7,11 +7,31 @@ permissions:
   pull-requests: write
 
 jobs:
-  Validate_commit_titles:
+  input_validation:
     runs-on: ubuntu-latest
     env:
       COMMITS_URL: ${{ github.event.pull_request.commits_url }}
+      PR_TITLE: ${{ github.event.pull_request.title }}
+      PR_DESCR: ${{ github.event.pull_request.body }}
     steps:
+      - name: Check PR details
+        run: |
+          valid=true
+          
+          if [[ ${#PR_TITLE} -lt 10 ]]; then
+            echo "::error::PR title is too small to convey any real meaning."
+            valid=false
+          fi
+          
+          if [[ ${#PR_DESCR} -lt 10 ]]; then
+            echo "::error::PR body is too small to convey any real meaning."
+            valid=false
+          fi
+          
+          if [[ $valid = false ]]; then
+            exit 1
+          fi
+      
       - name: Check commit titles
         run: |
           # get commits json and make an array of commit messages
